# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16OeF86jstWYEpLRWe2JyBMxpEBLwTY7J
"""

t1=()
print(t1)

t2=1,2,3
print(t2)

t3=(1,2,3)
print(t3)

t3=(1,2,3)
print(t3[0])

t3=1,2,3
a,b,c=t3
print('a=',a,'b=',b,'c=',c)

a=10
b=20
print('交換前','a=',a,'b=',b)
a,b=b,a
print('交換後','a=',a,'b=',b)

list1=[1,2,3,4]
t4=tuple(list1)
print(t4)

t4=(1,2,3,4)
t5=(t4,5,6)
print(t5)
print(len(t5))
print(t5[0][0])

t6=('z',)
print(t6)

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
print('購物清單shoplist為')
print(shoplist)

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
print('顯示shoplist[0]為',shoplist[0])

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
print('購物清單shoplist的長度為',len(shoplist))

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
shoplist[1]='皮蛋'
print("執行shoplist[1]='皮蛋'後")
print(shoplist)

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
index=shoplist.index('咖啡豆')
print("執行index=shoplist.index('咖啡豆')後")
print('index=',index)

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
shoplist.append('麵包')
print("執行shoplist.append('麵包')後")
print(shoplist)

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
shoplist.insert(4,'蘋果')
print("執行shoplist.insert('蘋果')後")
print(shoplist)

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
shoplist.remove('蛋')
print("執行shoplist.remove('蛋')後")
print(shoplist)

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
shoplist.pop(0)
print("執行 shoplist.pop(0)後")
print(shoplist)
shoplist.pop()
print("執行 shoplist.pop()後")
print(shoplist)
shoplist.pop(-1)
print("執行 shoplist.pop(-1)後")
print(shoplist)

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
del shoplist[0]
print("執行del shoplist(0)後")
print(shoplist)

shoplist=['milk','egg','cofee','watermelon']
shoplist.sort()
print("執行 shoplist.sort()後")
print(shoplist)

list=[1,2.0,3,'Python']
print("串列可以包含各種資料型別的元素")
print(list)

shoplist=['milk','egg','cofee','watermelon']
for item in shoplist:
    print(item)

shoplist1=['牛奶','蛋','咖啡豆']
shoplist2=['西瓜', '鳳梨']
shoplist_all=shoplist1+shoplist2
print(shoplist_all)

list3="2016/1/1".split('/')
print(list3)

