# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iGAR4ersCe3yk6UaJe26DBiaAE1RFO4F
"""

s=input('請輸入一行英文句子')
words=s.split(' ')
s3=s.title()
print('將每個單字自首轉大寫後,獲得句子為',words)


print('將英文句子以空白字元切割後,獲得的單字',words)
s2=' '.join(words)
print('以空白字元結合所有單字後,獲得句子後',s2)

