# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r7pg7KDx1BqXcIKbRdq3NWbEMRVGNull
"""

第一次期中考成績=int(input("請輸入第一次期中考成績?"))
第二次期中考成績=int(input("請輸入第二次期中考成績?"))
期末考成績=int(input("請輸入期末考成績?"))
總分=第一次期中考成績+第二次期中考成績+期末考成績
平均=(第一次期中考成績+第二次期中考成績+期末考成績)/3
print("總分為",總分)
print('平均為',平均)



x=float(input("請輸入幾尺?"))
y=float(input("請輸入幾吋?"))
公分=(x*12+y)*2.54
print("公制為",公分)

座號=int(input("請輸入座號?"))
print("計算結果顯示如下")
分組=座號/5
四捨五入=分組+1
分組為=int(四捨五入)
print("分組")
print(分組為)

u=float(input("輸入購買飲料的罐數"))
p=u/12
v=int(p)*200
r=0.5*12
f=int(r)*20
t=v+f
print("需花費",t)

