# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M0iIud2JkT-0wJQXjkzH8zNOTtR4btM_
"""

print(bool(1))

print(bool(0))

print(bool(()))

print(int(100))

print(int(3.14))

print(int("100",2))

print(float(1))

print(float(3.14))

print(float("3.1415"))

b=True

print(b,type(b))

num=20

print(num,type(num))

pi=3.14

print(pi,type(pi))

s="Hello"

print(s,type(s))

a=1

print(a,id(a))

a="Python"

print(a,id(a))

x=1

y=x

print(id(x),id(y))

print(x,y)

x=1
y=[1,2,3]
print(x in y)

x=1
y=[1,2,3]
print(x not in y)

x=[1,2,3]
y=[1,2,3]
print(x is y)

x=[1,2,3]
y=[1,2,3]
print(x is not y)

x=[1,2,3]
y=[1,2,3]
print(id(x),id(y))
print(x is y)
print(x == y)

s1="01234"
s2="56789"
s3=s1+s2
print(s3)

s1="01234"
s2=s1 * 2
print(s2)

s1='0123456789'
print(s1[0])
print(s1[1])
print(s1[-1])
print(s1[-2])

s='0123456789'
print('s=',s,'s[:]=',s[:])
print('s=',s,'s[5:]=',s[5:])
print('s=',s,'s[-2:]=',s[-2:])
print('s=',s,'s[:5]=',s[:5])
print('s=',s,'s[:-2]=',s[-2:])
print('s=',s,'s[7;9]=',s[7:9])
print('s=',s,'s[-4:-1]=',s[-4:-1])
print('s=',s,'s[5:-2]=',s[5:-2])
print('s=',s,'s[2:10:2]=',s[2:10:2])
print('s=',s,'s[::-1])=',s[::-1])
print('s=',s,'s[-1::-1]=',s[-1::-1])

s='春眠不覺曉，處處聞啼鳥。\n\夜來風雨聲，花落知多少。\\\t作者"孟浩然"詩名"春曉"'
print(s)

s1='春眠不覺曉，處處聞啼鳥，夜來風雨聲，花落知多少。'
list1=s1.split('，')

list1=['春眠不覺曉'，' 處處聞啼鳥'，'' 夜來風雨聲 '，'花落知多少。']
s2='，'.join(list1)
print(s2)

s1='春眠不覺曉 ，處處聞啼鳥 ，夜來風雨聲 ，花落知多少。'
s3=s1.replace('春','冬')
print(s3)

s1='春眠不覺曉， 處處聞啼鳥 ，夜來風雨聲 ，花落知多少。'
print(s1.find('花落'))

s1='春眠不覺曉 ，處處聞啼鳥， 夜來風雨聲， 花落知多少。'
s1.rfind('處')

s1='春眠不覺曉 ，處處聞啼鳥， 夜來風雨聲， 花落知多少。'
print(s1.startswith('春眠'))

s1='春眠不覺曉 ，處處聞啼鳥， 夜來風雨聲， 花落知多少。'
print(s1.endswith('多少。'))

s1='春眠不覺曉 ，處處聞啼鳥， 夜來風雨聲， 花落知多少。'
print(s1.count('處'))

s1='春眠不覺曉'
print(s1.center(10))

s1='春眠不覺曉'
print(s1.rjust(10))

s1='春眠不覺曉'
print(s1.ljust(10))

s1='an apple a day'
print(s1.title())

s1='An apple a day'
print(s1.title())

s1='An apple a day'
print(s1.swapcase())

s1='An apple a day'
print(s1.upper())

s1='An apple a day'
print(s1.lower())

s1='123'
print(s1.zfill(5))

s1='Hello,Mary.'
print(s1.strip())

s1='Hello,Marry.'
print(s1.lstrip('H'))

S1='Hello,Marry'
print(s1.rstrip('.'))

